---
# 
- name: invoke the role for /etc/iaac for hosts group iaas
  hosts: iaas
  become: yes
  roles:
    - role: create-iaac-file

- name: invoke the role for /etc/iaac for hosts group iaas
  hosts: all
  become: yes
  roles:
    - role: read-issue-content